import styled from "styled-components"
import Footer from "../components/Footer"
import NavigationBar from "../components/navigation/nav_bar"
<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;600&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@600&display=swap');
</style>
export default function TermsAndConditions(){
    return (
        <>
        <NavigationBar></NavigationBar>

        <PageDiv>


            <InfoDiv>
            <h1 style={{fontFamily:'Roboto+Mono', fontSize:'40px', fontWeight:'600', marginTop:'25px'}}>Termeni de utilizare</h1>
            <h3 style={{fontFamily:'Roboto+Mono', fontSize:'20px', color:'black',fontWeight:'300', marginTop:'15px', textAlign:'center'}} >Ultima actualizare: 14 iulie 2020</h3>
            <ParagraphDiv>
                <SubDivisionTitle>1. ACCEPTAREA TERMENILOR</SubDivisionTitle>

            <Text>1.1 Citiți cu atenție acești Termeni de utilizare („Termeni”) înainte ca Dvs. („Dumneavoastră”) să acceptați acești Termeni prin: (a) plasarea unei comenzi prin site și / sau (b) utilizând site-ul web („Website”) ) în orice alt mod. Dacă nu sunteți de acord cu toți acești termeni, nu utilizați acest site web.</Text>
            <Text>1.2 Condițiile sunt încheiate de și între firma noastrași Dvs. Dacă utilizați Serviciile în numele angajatorului dvs., declarați că sunteți autorizat să acceptați acești Termeni în numele angajatorului dvs. Firma noastra vă pune la dispoziție magazinul online firma noastra și alte resurse on-line accesibile prin firma noastra („Serviciile”), sub rezerva Condițiilor. Cu excepția cazului în care se prevede altfel în mod explicit, Termenii vor reglementa utilizarea de către dvs. a oricăror noi funcții care măresc sau îmbunătățesc Serviciile actuale, inclusiv lansarea de noi resurse firma noastra. În plus față de Termeni și cu excepția cazului în care se menționează altfel, licența standard firma noastra reglementează achizițiile pe care le efectuați prin firma noastra, cu excepția cazului în care aveți în prezent un contract separat de cumpărare scris sau acord de licență cu firma noastra pentru produsul respectiv, caz în care un acord separat guvernează.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>2. OBLIGAȚIILE DVS.</SubDivisionTitle>
                <Text>Având în vedere utilizarea de către dvs. a site-ului web și / sau a serviciilor, sunteți de acord să fiți singurul responsabil pentru: (a) furnizarea de informații adevărate, exacte, actuale și complete despre dvs., așa cum vi se solicită prin formularul de înregistrare al Serviciului („Datele de înregistrare”) și (b) menținerea și actualizarea promptă a datelor de înregistrare pentru a le menține adevărate, exacte, actuale și complete. Sunteți singurul responsabil pentru securitatea parolei. Firma noastra nu este responsabil pentru nicio utilizare neautorizată a site-ului web sau a serviciilor. Recunoașteți și sunteți de acord că anumite Servicii pot oferi acces restricționat prin parolă la informații despre clienți, cum ar fi numele și anumiți termeni ai contractelor dvs. existente, pentru a vă ajuta în achiziționarea, întreținerea și susținerea produselor dvs. firma noastra. Prin utilizarea acestui site web și înregistrarea pentru astfel de servicii, sunteți de acord cu firma noastra afișarea acestor informații prin intermediul Serviciilor și acceptă toate riscurile de acces neautorizat la astfel de informații. Dacă furnizați informații false, inexacte, depășite sau incomplete sau firma noastra are motive întemeiate să suspecteze că aceste informații sunt false, inexacte, nu sunt actuale sau incomplete, firma noastra vă poate suspenda sau termina contul. și să refuze orice utilizare actuală sau viitoare a Serviciilor (sau a oricărei părți a acestora).</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>3. CONFIDENȚIALITATEA INFORMAȚIILOR </SubDivisionTitle>
            <Text>Pentru a avea acces la Servicii, sunteți de acord cu aceste prevederi de confidențialitate:</Text>
            <Text>3.1 Confirmați că puteți obține acces direct prin intermediul site-ului web la anumite informații confidențiale firma noastra(„Informații”). Trebuie să păstrați informațiile în strictă încredere și puteți furniza informații angajaților din organizația dvs. numai pe baza necesității de a ști. Puteți utiliza informațiile de pe site-ul web numai în scopul achiziționării, întreținerii și susținerii produselor dvs. firma noastra. Titlul la informații rămâne la firma noastra și furnizorii săi. Sunteți de acord, fie ca persoană fizică, fie în numele angajatorului dvs., să fiți obligat de dispozițiile acestei secțiuni 3. În plus, dacă acționați în numele angajatorului dvs., angajatorul dvs. este de acord să despăgubească firma noastra pentru încălcările acestei secțiuni. 3.</Text>
            <Text>3.2 Nu obțineți niciun drept asupra informațiilor, cu excepția dreptului limitat la utilizarea informațiilor descrise mai sus.</Text>
            <Text>3.3 Orice încălcare a Condițiilor va avea ca rezultat un prejudiciu iremediabil pentru firma noastra pentru care daunele ar fi un remediu inadecvat și, prin urmare, pe lângă drepturile și remediile sale disponibile altfel în legislație, firma noastra va avea dreptul la o reparare echitabilă, inclusiv atât o hotărâre preliminară, cât și permanentă, dacă se produce o astfel de încălcare. Renunțați la orice cerință pentru înregistrarea unei obligațiuni sau a unei alte garanții în cazul în care firma noastra solicită o astfel de măsură.</Text>
            <Text>3.4 Obligațiile dvs. cu privire la informații expiră la cinci (5) ani de la data divulgării. La terminarea Termenilor sau a cererii scrise a firma noastra, trebuie să încetați utilizarea informațiilor și să returnați sau să distrugeți toate informațiile.</Text>
            <Text>3.5 Termenii nu îți impun nicio obligație cu privire la informațiile pe care le poți stabili prin dovezi suficiente din punct de vedere juridic: (a) ai posedat sau ai știut, înainte de primirea ta de la firma noastra, fără obligația de a-ți păstra confidențialitatea; (b) este sau devine în general cunoscut publicului prin niciun act sau omisiune de către dvs. sau în alt mod fără încălcarea Termenilor; (c) Ați obținut de la o terță parte care avea dreptul să le divulge, fără obligația de a păstra confidențialitatea acestor informații; (d) Te-ai dezvoltat independent fără utilizarea informațiilor și fără participarea persoanelor care au avut acces la informații sau (e) ca răspuns la o ordonanță valabilă a unei instanțe sau a unui alt organism guvernamental, după cum prevede altfel legea,</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>4. CONDUITA DUMNEAVOASTRĂ</SubDivisionTitle>
            <Text>4.1 Înțelegeți că toate informațiile, datele, textul, mesajele sau alte materiale („Conținut”), indiferent dacă sunt publicate public sau transmise în mod privat, sunt responsabilitatea exclusivă a persoanei de la care a provenit acest Conținut. Acest lucru înseamnă că dvs., și nu firma noastra, sunteți pe deplin responsabil pentru tot Conținutul pe care îl încărcați, postați sau transmiteți în alt mod prin intermediul Serviciilor. Firma noastra nu controlează Conținutul postat prin intermediul Serviciilor și, ca atare, nu garantează acuratețea, integritatea sau calitatea unui astfel de Conținut.</Text>
            <Text>4.2 Deși nu intenționăm să monitorizăm comunicările dvs. online, firma noastra își rezervă dreptul de a edita sau de a elimina conținutul despre care devenim conștienți și considerăm că este dăunător, ofensator sau care încalcă în alt mod acești Termeni. Firma noastra poate elimina, de asemenea, Conținutul care conține reclame comerciale ale unor terți, este inexact sau include divulgarea neautorizată sau informații personale. Încălcarea acestor restricții („Restricții”) poate duce, de asemenea, la închiderea sau suspendarea contului dvs. Aceste restricții se aplică întregului conținut furnizat către sau prin intermediul Serviciilor, inclusiv mesaje de e-mail, postări de grupuri de știri, chat și pagini web personale sau de afaceri.</Text>
            <Text>4.3 Sunteți de acord să nu postați sau să nu stocați pe firma noastra niciun conținut care încalcă sau încalcă drepturile de proprietate intelectuală ale oricui (inclusiv drepturi de autor, mărci comerciale, secrete comerciale, brevete, drepturi de publicitate sau (în măsura în care poate fi protejat) idei confidențiale) sau care este obscen, obscen în ceea ce privește minorii, pornografia infantilă, defăimător, rasist, obraznic, lasciv, murdar, excesiv de violent, hărțuitor sau în alt mod inacceptabil.</Text>
            <Text>4.4 Sunteți de acord să nu utilizați serviciile în niciun fel pentru spam sau pentru a transmite scrisori în lanț, e-mail nedorit sau comunicații în bloc. Sunteți de acord să nu utilizați niciun nume de domeniu firma noastra ca adresă de e-mail pseudonimă pentru comunicările pe care le transmiteți dintr-o altă locație sau printr-un alt serviciu; și este posibil să nu vă prefaceți că sunteți altcineva sau să vă falsați identitatea atunci când utilizați Serviciile. În plus, sunteți de acord să nu transmiteți comunicări nesolicitate sau în bloc către orice titular de cont firma noastra sau către orice adresă de e-mail firma noastra (indiferent dacă utilizați Serviciile pentru a transmite o astfel de comunicare).</Text>
            <Text>4.5 Sunteți de acord să nu utilizați Serviciile pentru activități ilegale care nu sunt acoperite altfel mai sus. În plus, sunteți de acord să nu utilizați Serviciile pentru:
•	identifica orice persoană sau entitate, incluzând, dar fără a se limita la, un oficial firma noastra sau să afirme în mod fals sau să denatureze în alt mod afilierea dvs. cu o persoană sau entitate;
•	falsificați anteturi sau manipulați altfel identificatori pentru a masca originea oricărui Conținut transmis prin Servicii sau pentru a dezvolta pagini sau imagini ascunse (cele care nu sunt legate de firma noastra dintr-o altă pagină accesibilă);
•	încărcați, postați sau transmiteți orice alt conținut pe care nu aveți dreptul să îl transmiteți publicului în temeiul niciunei legi sau în cadrul unor relații contractuale sau fiduciare (cum ar fi informații privilegiate, informații de proprietate sau confidențiale învățate sau dezvăluite ca parte a relațiilor de muncă sau sub nedivulgare acorduri);
•	încărcați, postați sau transmiteți orice alt material care conține viruși software sau orice alt cod de computer, fișiere sau programe concepute pentru a întrerupe, distruge sau limita funcționalitatea oricărui software de calculator sau hardware sau echipament de telecomunicații;
•	întrerupe fluxul normal de dialog, face ca un ecran să „deruleze” mai repede decât ceilalți utilizatori ai Serviciilor sunt capabili să introducă sau să acționeze în alt mod într-un mod care afectează negativ capacitatea altor utilizatori de a se angaja în schimburi în timp real;
•	încalcă în mod intenționat sau neintenționat orice lege locală, de stat, națională sau internațională aplicabilă sau orice reglementări cu putere de lege; sau
•	colectează sau stochează date personale despre alți utilizatori.</Text>
            
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>5. CONȚINUTUL TRIMIS </SubDivisionTitle>
            <Text>5.1 Firma noastra nu pretinde proprietatea asupra Conținutului pe care îl plasați pe site. Prin trimiterea de conținut către firma noastra pentru includere pe site, acordați și tuturor celorlalți utilizatori ai firma noastra o licență mondială, fără drepturi de autor și neexclusivă pentru a reproduce, modifica, distribui, transmite, afișa, efectua, adapta și publică conținutul (inclusiv în format digital).
</Text>
           <Text>5.2 Recunoașteți că firma noastra nu pre-examinează Conținutul, dar că firma noastra și persoanele desemnate de acesta au dreptul (dar nu obligația) la propria lor discreție de a bloca sau restricționa accesul la sau disponibilitatea sau dezactivarea, orice Conținut disponibil prin intermediul Serviciilor. Fără a limita cele de mai sus, firma noastra și reprezentanții săi pot dezactiva, restricționa accesul la sau disponibilitatea oricărui Conținut care încalcă Termenii sau care este inacceptabil în alt mod. Trebuie să evaluați și să suportați toate riscurile asociate cu utilizarea oricărui conținut, inclusiv orice dependență de acuratețea, caracterul complet sau utilitatea unui astfel de conținut.</Text>
           <Text>5.3 Cu excepția cazului în care se prevede altfel în mod explicit, în prezentul conținut, orice conținut furnizat de dvs. în legătură cu acest site web va fi considerat a fi furnizat pe o bază non-proprietară și neconfidențială. Firma noastra nu va avea nicio obligație de niciun fel cu privire la un astfel de Conținut și va fi liber să utilizeze sau să difuzeze un astfel de Conținut în mod nelimitat în orice scop. Recunoașteți că sunteți responsabil pentru conținutul pe care îl trimiteți și că dvs., nu firma noastra, aveți întreaga responsabilitate pentru conținut, inclusiv legalitatea, fiabilitatea, caracterul adecvat, originalitatea și drepturile lor de autor.</Text>
           
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>6. SPAM E-MAIL ȘI AFIȘĂRI</SubDivisionTitle>
            <Text>Sunteți de acord că firma noastra ar fi afectat iremediabil de utilizarea, de către dvs. sau de către alții, a Serviciilor sau facilităților firma noastra în legătură cu transmiterea de mesaje spam în grupuri de știri sau e-mailuri nesolicitate, cu încălcarea acestor Condiții, și că firma noastrae ste îndreptățit să obțină o despăgubire împotriva oricărei astfel de transmisii (pe lângă toate celelalte căi de atac disponibile în condițiile legii sau în echitate). Firma noastra își rezervă dreptul de a bloca, filtra sau șterge e-mailurile nesolicitate.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>7. INDEMNITATE</SubDivisionTitle>
            <Text>Sunteți de acord să despăgubiți și să dețineți firma noastra și filialele sale, afiliații, ofițerii, agenții, co-branderii, membrii alianței sau alți parteneri și angajați, inofensivi pentru orice cerere sau cerere, inclusiv onorariile rezonabile ale avocaților, făcute de orice terță parte din cauza sau care rezultă din conținutul dvs., utilizarea dvs. de către Servicii, inclusiv orice utilizare de către angajații Dvs., conexiunea dvs. la Servicii, încălcarea Dvs. a Condițiilor sau încălcarea Drepturilor alteia.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>8. ANUNȚURI; MODIFICAREA ȘI ÎNCETAREA SERVICIILOR</SubDivisionTitle>
            <Text>Firma noastra poate furniza notificări de modificări ale Termenilor sau alte aspecte afișând notificări sau linkuri către notificări către Dvs. în general pe Servicii. Firma noastra își rezervă dreptul în orice moment și din când în când de a modifica sau întrerupe, temporar sau permanent, Serviciile (sau orice parte a acestora) cu sau fără notificare prealabilă. Firma noastra poate aduce modificări magazinului online firma noastra, inclusiv în ceea ce privește produsele, serviciile, programele și prețurile, în orice moment, fără notificare prealabilă. Firma noastra, la propria sa discreție, poate rezilia parola dvs., utilizarea serviciilor dvs. sau utilizarea oricărui alt serviciu firma noastra și poate elimina și arunca orice conținut din cadrul serviciilor, din orice motiv, inclusiv, fără limitare, din lipsă de utilizare sau dacă firma noastra consideră că ați încălcat sau ați acționat neconcordant cu litera sau spiritul Termenilor. Orice încetare a accesului dvs. la Servicii conform oricărei prevederi a Termenilor poate fi efectuată fără o notificare prealabilă, iar firma noastra poate dezactiva sau șterge imediat contul dvs. și toate informațiile și fișierele aferente din contul dvs. și / sau poate interzice orice acces suplimentar către astfel de fișiere sau Servicii. Mai mult, firma noastra nu va fi răspunzător față de dvs. sau de orice terță parte pentru orice reziliere, modificare sau suspendare a Serviciilor.
9. PUBLICITĂȚI ȘI PROMOȚII
Firma noastra poate difuza reclame și promoții de la terți pe Servicii. Orice corespondență sau relații comerciale cu, sau participarea la promoții ale unor agenți de publicitate, alții decât firma noastra, găsite pe sau prin intermediul Serviciilor, inclusiv plata și livrarea de bunuri sau servicii conexe, precum și orice alte condiții, condiții, garanții sau reprezentări asociate cu astfel de tranzacții , sunt doar între dvs. și un astfel de agent de publicitate. Firma noastra nu este responsabilă sau răspunzătoare pentru orice pierdere sau daună de orice fel suferită ca urmare a unor astfel de tranzacții sau ca urmare a prezenței unor astfel de agenți de publicitate.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>10. LEGĂTURI</SubDivisionTitle>
            <Text>10.1 Serviciile pot furniza sau terți pot furniza linkuri către alte site-uri sau resurse de internet. Deoarece firma noastra nu are control asupra acestor site-uri și resurse, dvs. recunoașteți și sunteți de acord că firma noastra nu este responsabil pentru disponibilitatea unor astfel de site-uri sau resurse externe și nu susține și nu este responsabil sau răspunzător pentru orice Conținut, publicitate, produse sau alte materiale de pe sau disponibile de pe astfel de site-uri sau resurse. Firma noastra nu va fi responsabil sau responsabil, direct sau indirect, pentru orice daune sau pierderi cauzate sau presupuse a fi cauzate de sau în legătură cu utilizarea sau dependența de astfel de Conținut, bunuri sau servicii disponibile pe sau prin intermediul unui astfel de site sau resursă.</Text>
           <Text>10.2 Acest site web poate fi legat de alte site-uri web care nu sunt sub controlul și nu sunt întreținute de firma noastra. Firma noastra nu este responsabil pentru conținutul acestor site-uri. Firma noastra vă oferă aceste link-uri doar ca comoditate, iar includerea oricărui link către astfel de site-uri nu implică aprobarea de către firma noastra a acestor site-uri.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>11. DREPTURI DE PROPRIETATE INTELECTUALĂ</SubDivisionTitle>
            <Text>11.1 Serviciile și orice software (inclusiv orice descărcări disponibile pe site sau furnizate în alt mod de firma noastra) utilizate în legătură cu Serviciile („Software”) conțin informații proprietare și confidențiale care sunt protejate de proprietatea intelectuală aplicabilă și alte legi. Conținutul conținut în reclame terțe sau informații prezentate către dvs. prin intermediul Serviciilor sau agenților de publicitate pot fi protejate de drepturi de autor, mărci comerciale, mărci de servicii, brevete, drepturi de publicitate sau alte drepturi și legi de proprietate. Cu excepția cazului în care este autorizat în mod expres de firma noastra sau de agenții de publicitate, sunteți de acord să nu modificați, să închiriați, să închiriați, să împrumutați, să vindeți, să distribuiți sau să creați lucrări derivate pe baza Serviciilor sau a Software-ului, în totalitate sau parțial.</Text>
            <Text>11.2 Puteți utiliza software-ul și serviciile conexe numai sub rezerva acordului sau licenței care însoțește acest software sau servicii. Puteți utiliza Serviciile numai pe durata specificată a acestora, pentru numărul enumerat de ori, pentru numărul specificat de persoane fizice, sau așa cum este limitat în acordul sau licența aplicabilă. Serviciile care implică o actualizare, lansarea versiunii, lansarea produsului, lansarea întreținerii, patch-uri sau lucrări derivate ale unui software sau serviciu licențiat pot fi utilizate numai: (a) pe sistemele pentru care un astfel de software sau serviciu au fost autorizate în mod specific; și (b) sub rezerva licenței și a termenului de garanție care reglementează produsul sau Serviciul original.</Text>
           <Text>11.3 Nu trebuie să modificați, să decompilați sau să faceți inginerie inversă niciun software pe care firma noastra vi-l dezvăluie și nu trebuie să eliminați, să suprimați sau să eliminați orice notificare privind drepturile de autor, mărci comerciale, sigle, legende sau alte notificări de proprietate din orice original sau copie. de software sau informații din Servicii.</Text>
            <Text>11.4 „Mărci comerciale firma noastra ” înseamnă toate numele, mărcile, mărcile, siglele, desenele, îmbrăcămintea comercială și alte denumiri pe care firma noastra le folosește în legătură cu Produse sau Servicii. Clientul nu poate elimina sau modifica orice mărci comerciale ale noastre. Clientul recunoaște drepturile asupra mărcilor comerciale firma noastra. Clientul este de acord să nu încorporeze mărci comerciale firma noastra în mărcile comerciale ale clientului, mărcile de servicii, numele companiilor, adresele de internet, numele domeniilor sau orice alte denumiri similare.</Text>
            <Text>11.5 Firma noastra se angajează să respecte drepturile de proprietate intelectuală ale altora și le cerem utilizatorilor noștri să facă același lucru. Firma noastra  poate, la propria sa discreție, să rezilieze conturile sau drepturile de acces ale utilizatorilor care încalcă sau încalcă în alt mod drepturile de proprietate intelectuală ale altor persoane. Dacă credeți că lucrarea dvs. a fost copiată într-un mod care constituie o încălcare a drepturilor de autor pe firma noastra, vă rugăm să contactați agentul nostru pentru drepturile de autor așa cum este descris în politica noastră privind drepturile de autor.</Text>
            <Text>11.6 Tot conținutul furnizat pe acest site web este furnizat de către sau către firma noastra de către producătorii, autorii, dezvoltatorii și furnizorii respectivi („furnizorii terți”) și este opera protejată prin drepturi de autor a firmei noastre și / sau a furnizorilor terți. Cu excepția celor menționate aici, niciunul din Conținut nu poate fi copiat, reprodus, distribuit, republicat, descărcat, afișat, postat sau transmis în orice formă sau prin orice mijloace, inclusiv, dar fără a se limita la, electronice, mecanice, fotocopiere, înregistrare sau în caz contrar, fără permisiunea expresă prealabilă scrisă a firmei noaste sau a furnizorului terț. Nicio parte a site-ului web, inclusiv siglele, grafica, sunetele sau imaginile, nu poate fi reprodusă sau retransmisă în niciun fel sau prin orice mijloace, fără permisiunea prealabilă scrisă prealabilă a firmei noastre. De asemenea, nu puteți, fără permisiunea scrisă prealabilă a firmei noastre.</Text>
           <Text>11.7 Nimic de pe acest site web nu poate fi interpretat ca conferind o licență în temeiul oricărui drept de proprietate intelectuală al firmei noastre sau al oricărui furnizor terț, fie prin estoppel, implicare sau altfel. Confirmați responsabilitatea exclusivă pentru obținerea unor astfel de licențe.</Text>
           <Text>11.8 Se acordă permisiunea de a afișa, copia, distribui și descărca conținutul firmei noastre pe acest site web, cu condiția ca: (1) atât notificarea privind drepturile de autor identificate mai jos, cât și această notificare de autorizare să apară în conținut, (2) utilizarea unui astfel de conținut este exclusiv pentru uz personal, necomercial și informațional și nu vor fi copiate sau postate pe niciun computer din rețea sau difuzate pe niciun suport, cu excepția cazului în care este permis în mod explicit de licența valabilă care acoperă astfel de materiale și (3) nu se fac modificări ale conținutului . Această permisiune se încheie automat fără notificare în cazul în care încălcați oricare dintre acești termeni sau condiții. La terminare, trebuie să distrugeți imediat orice conținut descărcat și tipărit.</Text>
           <Text>11.9 Orice utilizare neautorizată a oricărui conținut conținut pe acest site web poate încălca legile drepturilor de autor, legile mărcilor comerciale, legile privind confidențialitatea și publicitatea, precum și reglementările și statutele de comunicare.
11.10 Conținutul furnizat de furnizori terți nu a fost autentificat în totalitate sau parțial de către firma noastra. Firma noastra nu furnizează, nu vinde, licențiază sau închiriază niciun alt conținut decât cele identificate în mod specific ca fiind furnizate de firma noastra.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>12. DECLINARE DE GARANȚII</SubDivisionTitle>
            <Text>12.1 UTILIZAREA DUMNEAVOASTRĂ A SERVICIILOR ȘI A ORICĂRUL SOFTWARE ESTE LA RISCUL DUMNEAVOASTRĂ. SOFTWARE-UL, SERVICIILE ȘI INFORMAȚIILE SUNT FURNIZATE PE „CA ATARE” ȘI „CÂT DISPONIBIL”. CONȚINUTUL PE SITE-UL WEB ESTE OFERIT „CA ATARE”, „CU TOATE DIFECTURILE” ȘI ESTE DOAR PENTRU UTILIZARE COMERCIALĂ. FIRMA NOASTRA DECLARA TOATE CONDIȚIILE EXPRESE SAU IMPLICITE, REPREZENTAȚIILE ȘI GARANȚIILE DE ORICE TIP, INCLUSIV ORICE GARANȚIE IMPLICITĂ SAU CONDIȚIA DE VANZABILITATE, ADEVĂRUL PENTRU UN SCOP PARTICULAR, TITLU, DISFRUTARE SILINȚĂ SAU NEINFRACTIONARE. FIRMA NOASTRA NU FACE REPREZENTĂRI, GARANȚII, CONDIȚII SAU GARANȚII PRIVIND CALITATEA, ADECVAREA, ADEVĂRUL, EXACTITATEA SAU COMPLETITATEA ORICĂRIE A CONȚINUTULUI CONȚINUT PE SITE-UL WEB. FIRMA NOASTRA POATE DISPONIBILA PE CONȚINUTUL SITE-ULUI DISPONIBIL PENTRU DESCĂRCAREA CARE A FOST TRIMITUTĂ DE UTILIZATORI TERȚI ai SITE-ULUI. ORICE ÎNTREBARE PRIVIND CONȚINUTUL TREBUIE SĂ FIE DIRECȚIONAT PRESTATORILOR ASUPRA CONȚINUTULUI. În niciun caz, firma noastra sau furnizorii săi nu vor fi răspunzători pentru acuratețea sau completitudinea conținutului sau a informațiilor de pe site.</Text>
            <Text>12.2 FIRMA NOASTRA NU OFERĂ NICI O GARANȚIE SAU REPREZENTARE CĂ: (i) SOFTWAREULUI SAU SERVICIILE VĂ ÎNDEPLINESC CERINȚELE DUMNEAVOASTRĂ, (ii) SERVICIILE VOR FI NEINTERTRUPTE, TIMPALE, SIGURANTE SAU FĂRĂ ERORI, (iii) REZULTATELE CARE POT FI OBȚINUTE DIN UTILIZAREA SOFTWAREULUI SAU A SERVICIILOR VA FI ACURĂ SAU DE FIABILITATE, (iv) CALITATEA ORICĂROR PRODUSE, SOFTWARE, SERVICII, INFORMAȚII SAU ALTE MATERIALE CUMPĂRATE SAU OBȚINUTE DE DUMNEAVOASTRĂ PRIN SERVICIILE VĂ ÎNDEPLINESC AȘTEPĂTĂTURILE DVS. ORICE ERORI DIN SOFTWARE VOR FI CORECTATE.</Text>
           <Text>12.3 ORICE MATERIAL DESCĂRCAT SAU OBȚINUT ÎN ALT MOD PRIN UTILIZAREA SERVICIILOR SE FACE LA PROPRIA DISCREȚIE ȘI RISC ȘI EȘTI SINGUR RESPONSABIL PENTRU ORICE DETERIORARE A SISTEMULUI DE CALCULATOR SAU PIERDEREA DE DATE CARE REZULTĂ DIN DESCĂRCAREA UNUI MATERIAL ASUPRA. REZULTAT DE LA VIRUSURI INFORMATICE.</Text>
           <Text>12.4 NICIUN SFAT ȘI INFORMAȚIE, ORALĂ SAU SCRISĂ, OBȚINUTĂ DE DUMNEAVOASTRĂ DE LA FIRMA NOASTRA SAU PRIN SAU DIN SERVICII, NU VA CREA NICI O GARANȚIE SAU CONDIȚIE NECESĂ EXPRESĂ ÎN TERMENI. ANGAJAȚII FIRMA NOASTRA NU SUNT AUTORIZATI SĂ VARIE ACESTI TERMENI.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>13. LIMITAREA RESPONSABILITĂȚII</SubDivisionTitle>
            <Text>13.1 ÎN MĂSURA DE INTERZICERE A LEGII APLICABILE, FIRMA NOASTRA NU ESTE RESPONSABILĂ PENTRU NICI UN DOMENIU DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSECUȚIAL, PUNITIV, SAU EXEMPLAR, INCLUSIV, DAR NE LIMITAT LA, DAUNE PENTRU PIERDEREA PROFITULUI, VENITURI, BUNA FĂCUTĂ, UTILIZARE, DATE, COMENZI TRANSMISE ELECTRONIC SAU ALTE AVANTAJE ECONOMICE (CHIAR DACĂ FIRMA NOASTRA A FOST AVIZAT DE POSIBILITATEA ASUPRA DAUNELOR), ORICUM A CAUZAT ȘI INDIFERENT TEORIA RESPONSABILITĂȚII, FIE ÎN CONTRACT (INCLUSIV) INCLUSIV NEGLIGENȚA) SAU ÎN ALTĂ MODALITATE, REZULTAT DIN SAU LEGAT DE: (i) UTILIZAREA SAU INCAPABILITATEA DE A UTILIZA SOFTWARE-UL SAU SERVICIILE; <br></br>(ii) COSTUL DE ACHIZIȚIE A MĂRFURILOR ȘI A SERVICIILOR SUBSTITUTE REZULTATE DIN ORICE MARFĂ, DATE, SOFTWARE, INFORMAȚII SAU SERVICII CUMPĂRATE SAU OBȚINUTE SAU MESAJE PRIMITE SAU TRANZACȚII INTREPRINDERE PRIN SAU DIN SERVICII; <br></br> (iii) ACCESUL NEAUTORIZAT LA ALTERAREA TRANSMISIILOR SAU A DATELOR DUMNEAVOASTRĂ; <br></br>(iv) DECLARAȚII SAU CONDUITELE ORICĂREI TERȚI PRIVIND SERVICIILE ȘI SITE-UL WEB; <br></br>SAU (v) ORICE ALT MATERIE LEGATĂ DE SERVICII, INCLUSIV CONȚINUTUL PE CARE O PUTEȚI DESCĂRCA, UTILIZA, MODIFICA SAU DISTRIBUI DE PE SITE-UL. FĂRĂ A CONTRA ÎN CONTRAR ÎN ACESTE TERMENI DE UTILIZARE, RĂSPUNDEREA NOSTRU CUMULATIVĂ ÎN FAȚĂ DUMNEAVOASTRĂ CĂTRE O CAZĂ Oricare și indiferent de forma acțiunii, va fi, în orice moment, limitată la 100,00 USD (O Sută de Dolari). INCLUSIV CONȚINUTUL PE CARE SE POATE DESCĂRCA, UTILIZA, MODIFICA SAU DISTRIBUI DE PE SITE-UL. FĂRĂ A CONTRA ÎN CONTRAR ÎN ACESTE TERMENI DE UTILIZARE, RĂSPUNDEREA NOSTRU CUMULATIVĂ ÎN FAȚĂ DUMNEAVOASTRĂ CĂTRE O CAZĂ Oricare și indiferent de forma acțiunii, va fi, în orice moment, limitată la 100,00 USD (O Sută de Dolari). INCLUSIV CONȚINUTUL PUTEȚI SĂ DESCĂRCAȚI, UTILIZA, MODIFICA SAU DISTRIBUI DE PE SITE. FĂRĂ A CONTRA ÎN CONTRAR ÎN ACESTE TERMENI DE UTILIZARE, RĂSPUNDEREA NOSTRU CUMULATIVĂ ÎN FAȚĂ DUMNEAVOASTRĂ CĂTRE O CAZĂ Oricare și indiferent de forma acțiunii, va fi, în orice moment, limitată la 100,00 USD (O Sută de Dolari).  DACĂ ESTEȚI UN REZIDENT AL CALIFORNIEI, RENUNȚAȚI DE LA DISPOZIȚIILE SECȚIUNII 1542 CODUL CIVIL AL CALIFORNIEI, CARE PREVEDE CĂ O ELIBERARE GENERALĂ NU SE EXTENDEZĂ LA RECLAMĂRILE PE CARE CREDITORUL NU ȘTIE ȘI NU SUSPECTEZĂ SĂ EXISTĂ ÎN TIMPUL SĂU ȘI AL SĂU FAVOR ELIBERAREA.  </Text>
           <Text>13.2 AVEȚI UNICĂ RESPONSABILITATE PENTRU PROTECȚIA ȘI backup-ul adecvat al datelor și / sau echipamentelor utilizate în legătură cu site-ul web și nu veți face o revendicare împotriva firma noastra PENTRU DATELE PIERDUTE, TIMP REALIZAT, IEȘIREA INACURĂ, ÎNTÂRZIERI LA MUNCĂ SAU REZULTATELE PROFITURILOR PIERDUTE DIN UTILIZAREA CONȚINUTULUI.</Text>
            <Text>13.3 SUNTEȚI DE ACORD SĂ PĂSTRAȚI FIRMA NOASTRA INFORMAȚI DE LA, ȘI PĂLȚIȚI SĂ NU SUMAȚI FIRMA NOASTRA PENTRU ORICE REVENDICARE BAZATĂ PE UTILIZAREA SITE-ULUI, FIE ÎN CONTRACT (INCLUSIV ÎNCĂLCAREA FUNDAMENTALĂ), TORT (INCLUSIV NEGLIGENȚA) SAU ALTU. Unele jurisdicții nu permit excluderea sau limitarea daunelor accidentale sau consecutive, astfel încât este posibil ca limitarea sau excluderea de mai sus să nu se aplice pentru dvs.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>14. INFORMAȚII GENERALE</SubDivisionTitle>
            <Text>14.1 Cu excepția celor stabilite mai sus, Termenii constituie întregul acord între dvs. și firma noastra referitor la obiectul lor și guvernează utilizarea de către dvs. a serviciilor, înlocuind orice acorduri anterioare dintre dvs. și firma noastra (inclusiv, dar fără a se limita la, orice versiuni anterioare ale Termenilor). De asemenea, este posibil să fiți supus unor termeni și condiții suplimentare care se pot aplica atunci când utilizați alte servicii firma noastra, conținut terță parte sau software terță parte. Nu trebuie să atribuiți sau să transferați în alt mod Termenii și niciun drept acordat prin prezenta. Secțiunile 3, 4, 10, 11, 12, 13 și 14 supraviețuiesc încetării Termenilor.</Text>
           <Text>14.2 Acești Termeni vor fi guvernate de, și interpretate și aplicate în conformitate cu legile statului Utah, fără a ține cont de principiile conflictelor de legi. Convenția Organizației Națiunilor Unite privind contractele de vânzare internațională de bunuri este în mod expres respinsă. Orice cauză de acțiune a dvs. cu privire la site-ul web (inclusiv, dar fără a se limita la acești termeni) trebuie instituită în termen de un an de la apariția cauzei acțiunii sau trebuie renunțată și exclusă pentru totdeauna. Sunteți de acord că orice reclamație sau dispută pe care o aveți împotriva firma noastra care rezultă din sau este legată de utilizarea site-ului web sau a acestor Termeni trebuie soluționată exclusiv de o instanță de stat sau federală situată în județul Sale Lake, Utah. Sunteți de acord să vă supuneți jurisdicției personale a instanțelor situate în județul Salt Lake, Utah, în scopul litigării tuturor acestor reclamații sau litigii</Text>
            <Text>14.3 Firma noastra controlează și operează acest site web de la sediul său din Statele Unite ale Americii și nu face nicio declarație că acest conținut este adecvat sau disponibil pentru utilizare în alte locații. Dacă utilizați acest site web din alte locații, sunteți responsabil pentru respectarea legilor locale aplicabile, inclusiv, dar fără a se limita la, reglementările de export și import din alte țări.</Text>
            <Text>14.4 Recunoașteți și sunteți de acord că conținutul poate fi supus legilor și regulamentelor SUA privind administrarea exporturilor. Este interzisă devierea unui astfel de conținut contrar legislației SUA. Sunteți de acord că niciunul dintre Conținuturi și niciun produs direct din acesta nu este sau va fi achiziționat pentru, expediat, transferat sau reexportat, direct sau indirect, în țări interzise sau embargotate sau resortisanții acestora și nici nu va fi utilizat pentru activități nucleare , arme chimice biologice sau proiecte de rachete, cu excepția cazului în care este autorizat de guvernul SUA. Sunteți de acord să respectați strict toate legile de export din SUA și vă asumați responsabilitatea exclusivă pentru obținerea licențelor de export sau reexport, după cum este necesar.</Text>
            <Text>14.5 Acest site web poate include inexactități sau erori tipografice. Firma noastra și furnizorii terți pot face îmbunătățiri și / sau modificări ale produselor, serviciilor, programelor și prețurilor descrise în acest site web în orice moment fără notificare prealabilă. Modificările se efectuează periodic pe site. Firma noastra poate modifica acești Termeni în orice moment prin postarea termenilor modificați pe acest site.</Text>
            <Text>14.6 Eșecul firma noastra de a exercita sau de a aplica orice drept sau prevedere a Termenilor nu constituie o renunțare la acest drept sau prevedere. Dacă o instanță cu jurisdicție competentă consideră că orice prevedere a Termenilor este invalidă, părțile convin totuși că instanța ar trebui să depună eforturi pentru a pune în aplicare intențiile părților, astfel cum se reflectă în dispoziție, iar celelalte dispoziții ale Termenilor rămân în vigoare deplină și efect. Indiferent de orice statut sau lege contrară, orice reclamație sau cauză de acțiune care decurge din sau legată de utilizarea Serviciilor sau a Termenilor trebuie depusă în termen de un (1) an de la apariția acestei reclamații sau cauză de acțiune sau să fie exclusă pentru totdeauna . Titlurile secțiunilor din Termeni sunt doar pentru comoditate și nu au niciun efect legal sau contractual.</Text>
           <Text>14.7 Cu excepția celor specificate mai sus, acești Termeni reprezintă întreaga înțelegere referitoare la utilizarea site-ului web și prevalează asupra oricărei comunicări anterioare sau contemporane, conflictuale sau suplimentare.</Text>
            </ParagraphDiv>
            <ParagraphDiv>
                <SubDivisionTitle>15. FORUMURILE UTILIZATORILOR</SubDivisionTitle>
            <Text>15.1 Forumurile pentru utilizatori sunt destinate comunității de utilizatori firma noastra și firma noastra pentru a partaja informații reciproc și pentru a solicita asistență din partea personalului de asistență firma noastra.</Text>
            <Text>15.2 Forumurile sunt moderate în măsura în care postările ar trebui să fie relevante pentru 15.1 de mai sus. Spamul, rasismul, inundațiile, reclamele, scrisorile în lanț, schemele piramidale, solicitările, pornografia și limbajul jignitor sunt interzise. Orice postări care nu oferă valoare comunității de utilizatori sau sunt evident ofensatoare vor fi eliminate de moderatori.</Text>
            <Text>15.3 Prin înregistrarea unui cont verificând „Sunt de acord” pe formularul de înregistrare, garantați că sunteți singurul responsabil pentru conținutul mesajului dvs. postat. În plus, sunteți de acord să despăgubiți și să mențineți inofensiv firma noastra, personalul său, filialele sale și orice site-uri web conexe.</Text>
            <Text>15.4 Cu fiecare postare pe forum, adresa dvs. IP este înregistrată, în cazul în care trebuie să fiți interzis de la acest forum sau să fiți contactat de ISP. Acest lucru se va întâmpla numai în cazul unei încălcări majore a acestui acord.</Text>
           <Text>15.5 Postările făcute pe forumuri pot fi vizualizate public prin intermediul site-ului web firma noastra. Abțineți-vă de la postarea oricărei informații confidențiale. Deoarece forumurile sunt disponibile publicului, postările pot fi încă vizibile din diferite servicii cache și motoare de căutare mult timp după ce au fost șterse. </Text>
           <Text>15.6 Membrii personalului de asistență firma noastra frecventează forumurile și încearcă să răspundă la toate întrebările și comentariile în timp util. Cu toate acestea, nu există nicio garanție că se va răspunde la orice întrebare într-un anumit interval de timp. </Text>
            </ParagraphDiv>
            </InfoDiv>
            
        </PageDiv>
        <Footer></Footer>

</>
    )
}

const PageDiv = styled.div`
display: flex;
flex-direction: column;
align-items: center;
background-color: rgba(0,0,0,0.7);
`

const InfoDiv = styled.div`
background-color: white;
width: 70%;
margin-top: 20px;
margin-bottom: 20px;
`

const ParagraphDiv = styled.div`
display: flex;
flex-direction: column;
/* width: 65%; */
font-family: 'Roboto+Mono';
margin-top: 40px;
margin-bottom: 40px;
padding: 15px;
align-items: center;
text-align: justify;
`

const Text = styled.p`
font-weight: 300;
font-size: 20px;
padding: 10px;
margin-top: 10px;
text-indent: 25px;
text-align: justify;
`
const SubDivisionTitle = styled.h2`
color: black;
font-weight: 600;
font-size: 25px;
`